### PR TITLE
sync latest changes from terence's eip rebase repo

### PR DESCRIPTION
**Pull request by roberto-bayardo**
pull latest changes from terence's eip4844 rebasing repo into the branch used by Inphi/eip4844-interop repo.

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
Thanks for doing this.

**Comment by roberto-bayardo** [comment]
Turns out I wasn't testing it properly and it doesn't actually work yet...  will try to debug tomorrow.

**Comment by roberto-bayardo** [comment]
Hey @terencechain I'm trying to get these commits from your eip4844 prysm repo to work with Mofi's eip4844-interop repo e2e test.   I've patched some initial issues but right now I'm seeing the beacon-node repeatedly validate the merge block ... so it is just displaying the big panda over and over without making any progress.  Any ideas?

**Comment by terencechain** [comment]
Hi, how to reproduce?

**Comment by roberto-bayardo** [comment]
clone https://github.com/Inphi/eip4844-interop  and then "make devnet-up" to make sure it's working (you should see the beacon-node advancing properly....)

then cd into the prysm submodule and checkout my branch (roberto-bayardo/update-rebase) ... "make devnet-clean" followed by "make devnet-up" and then you should see the beacon-node failing to make progress.

**Comment by roberto-bayardo** [comment]
The following commit is the first one where I notice the e2e test starts failing:

"[Encapsulate sidecar within signed block interface](https://github.com/Inphi/prysm/pull/12/commits/a390c74721990bf9aec6eb1bb58e8a2f2111f7ee)"

The sidecar pointer is added at the top level and since the Block type has a non-pointer receiver, setting the sidecar is a no-op (it modifies only a temporary copy).

There's a good chance this is fixed in a later change as it seems later commits affect this particular code quite a bit, so not sure if this is going to end up relevant to the current issue.

**Comment by Inphi** [comment]
> There's a good chance this is fixed in a later change as it seems later commits affect this particular code quite a bit, so not sure if this is going to end up relevant to the current issue.

Do you mean this bug could be fixed on the latest upstream? Prysm just put out a 3.0 merge release. Worth rebasing that since that should be stable enough.

**Comment by terencechain** [comment]
> > There's a good chance this is fixed in a later change as it seems later commits affect this particular code quite a bit, so not sure if this is going to end up relevant to the current issue.
> 
> Worth rebasing that since that should be stable enough.

I've rebased it here: https://github.com/terencechain/prysm/pull/1

**Comment by roberto-bayardo** [comment]
I just rebased against the latest version of @terencechain 's eip repo to get the v3 changes in but chain is still not advancing.  Will continue digging....

**Comment by roberto-bayardo** [comment]
Let me close this PR as it's become quite a mess. I'll re-open when I get things in a better state.

**Comment by terencechain** [comment]
> clone https://github.com/Inphi/eip4844-interop and then "make devnet-up" to make sure it's working (you should see the beacon-node advancing properly....)
> 
> then cd into the prysm submodule and checkout my branch (roberto-bayardo/update-rebase) ... "make devnet-clean" followed by "make devnet-up" and then you should see the beacon-node failing to make progress.

~~`make devnet-up` failed `#0 0.329 go: go.mod file not found in current directory or any parent directory; see 'go help modules'`... Will look into this...~~

Resolved. Sorry for the noise. Fixing the flags now

**Comment by roberto-bayardo** [comment]
Oh sorry that roberto-bayardo/update-rebase branch is now obsolete.   You
can just use your own prysm rebase repo here to replicate though:
terencechain#1 <https://github.com/terencechain/prysm/pull/1>

or you can try my latest v3 branch: update-rebase-2

**Comment by terencechain** [comment]
I've taken a closer look...
The first issue is it fails to propose a block at the start. Times out when broadcasting. `--min-sync-peers=0` in docker-compose didn't work for me for some reason. I manually added it to `run_beacon_node.sh`, and that's been resolved
The second issue is post-Bellatrix, the node is always in optimistic mode. This is usually due to the execution layer client up and how ttd is configured. I haven't had a chance to look into this yet

**Comment by roberto-bayardo** [comment]
yeah I was seeing that too so just for grins I coded "isOptimistic" to always return false, but at that point I just see it re-proposing the fork block over and over again.

**Comment by Inphi** [comment]
The old clean-slate branch made a couple changes to optimistic sync and fork choice. We no longer need those changes with coupled blocks. Wanna make sure that those changes werent merged here.

**Pull request closed without merging**
